version: '3.8'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./public:/var/www/public
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php-fpm
  #     - db

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tech-php
    ports:
      - "8000:8000"
    volumes:
      - ./serve:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
