version: '3.8'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./public:/var/www/public
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php-fpm
  #     - db

  client-vuejs:
    build:
      context: .  # Caminho para o Dockerfile do cliente Vue.js
      dockerfile: docker/vuejs/Dockerfile
    container_name: vuejs-client
    ports:
      - "3000:80"  # Mapeia a porta 3000 do host para a porta 80 do contêiner
    # depends_on:
    #   - backend  # Supondo que você tenha um serviço backend no Docker Compose

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tech-php
    ports:
      - "8000:8000"
    volumes:
      - ./serve:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    # restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
